services:
  hospital-app:
    container_name: hospital-app
    depends_on:
      hospital-db:
        condition: service_healthy
    image: 'hostpital-app:latest'
    build:
      no_cache: true
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: 'hospital-db'
    ports:
      - 8085:8085
  hospital-db:
    container_name: hospital-db
    image: mysql:8.0.31
    restart: always
    ports:
#       hostPort:containerPort
      - "33062:3306"
    volumes:
      - my-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 7s
      retries: 2

# Names our volume
volumes:
  my-db: